# Postgres
#   gem install pg
#
#   Ensure the pg gem is defined in your Gemfile
#   gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  reconnect: false
  host: localhost
  port: 5432

development:
  adapter: postgresql
  # database: pettycash
  database: messager
  username: postgres
  password: test

production:
  adapter: postgresql
  database: <%= ENV['RDS_DB_NAME']%>
  username: <%= ENV['RDS_USERNAME']%>
  password: <%= ENV['RDS_PASSWORD']%>
  host: <%= ENV['RDS_HOSTNAME']%>
  port: <%= ENV['RDS_PORT']%>
